### 회원가입
POST http://localhost:8080/api/members
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "kim",
  "password": "1234",
  "phone": "010-1111-2222"
}

### 회원정보수정
PUT http://localhost:8080/api/members
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "example",
  "phone": "01012345678"
}

### 회원탈퇴
DELETE http://localhost:8080/api/members
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}

> {%
    client.log(response.body.token)
    client.global.set("auth_token", response.body.token)
%}

### 비밀번호변경
PUT http://localhost:8080/api/members/password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "password": "12345678"
}
